### ISSUE TITLE
AWS Information

### ISSUE THREAD

**Issue by samagraa91** [rainu/wow-quest-reader#1]
Sorry, it's not an issue but can you provide more details on how to fill out the config.yml including how to get the information from AWS?

**Comment by rainu** [comment]
Hey,
to get your AWS credentials you have basically do the following:
* login in AWS console
* Go to `IAM`
* Create a new user
   * This user needs the permission for Polly
   * The easiest way is to attach the policy `AmazonPollyFullAccess`
* Generate/Get the user's credentials
   * choose the user
   * goto `Security credentials `
   * Create `Access Key`
   * Take the `Access key`-Value (*AK...*) and `Secret access key`-Value (*S3/...*) and put them in config.yml
* Choose the region you want (see AWS-Blog)[https://aws.amazon.com/de/blogs/architecture/what-to-consider-when-selecting-a-region-for-your-workloads/]

```yml
sound:
  aws:
    region: "eu-central-1"
    key: "AK..."
    secret: "S3/..."
```

**Comment by samagraa91** [comment]
Thank you! Got it working!
